#! /bin/bash
set -x
### BEGIN INIT INFO
# Provides:          honeyPot
# Should-Start:      
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: honey pot for various services
# Description:       Debian init script for the HoneyPot
### END INIT INFO

###Vars /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
logfile='honeyPi.log'
logfolder='/var/log/honeyPi'
logFile='$logfolder/$logfile'
honeyPATH=''
export PATH=$PATH:/opt/dionaea/bin
###Funcs ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
log_chk(){
	if [ ! -e $logfolder ];then
		mkdir $logfolder -m 775
			if [ ! -e $logfile ];then
				touch $logfile
			fi
	fi
	}

honey_start(){
		apacheSts=`/etc/init.d/apache2 status >> /dev/null ;echo $?`
	if [ "$apacheSts" == "0" ];then
	cd /opt/glastopfi && glastopf-runner
	else
		echo "apache dependencies - please start apache: systemctl start apache2.service"
		exit 1
	fi

	dionaea -l all,debug -r /opt/dionaea -w /opt/dionaea -p /opt/dionaea/var/dionaea.pid
	python /opt/ragpicker/ragpicker.py -t 5 --log-filename=$logfolder/ragpicker.log
	cd /opt/honssh;./honsshctrl START
	cd /opt/kippo-read-only;./start.sh
	}

honey_stop(){
		sts_glastopf=`ps aux |grep glastopf >> /dev/null;echo $?`
		sts_dionaea=`ps aux | grep dionaea >> /dev/null;echo $?`
		sts_ragpicker=`ps aux| grep ragpicker >> /dev/null;echo $?`
		sts_honssh=`ps aux |grep honssh >> /dev/null; echo $?`
		sts_kippo=`ps aux|grep kippo >>/dev/null ;echo $?`
		
		if [ "$sts_glastopf" == '0' ];then
			killall glastopf 
		fi
		if [ "$sts_dionaea" == '0' ];then
			killall dionaea
		fi
		if [ "$sts_ragpicker" == '0' ];then
			killall  ragpicker
		fi
		if [ "$sts_honssh" == '0' ];then
			killall honssh
		fi
		if [ "$sts_kippo" == '0' ];then
			killall kippo
		fi
	
	}

honey_restart(){
	
	
	}

honey_status(){
		sts_glastopf=`ps aux |grep glastopf >> /dev/null;echo $?`
		sts_dionaea=`ps aux | grep dionaea >> /dev/null;echo $?`
		sts_ragpicker=`ps aux| grep ragpicker >> /dev/null;echo $?`
		sts_honssh=`ps aux |grep honssh >> /dev/null; echo $?`
		sts_kippo=`ps aux|grep kippo >>/dev/null ;echo $?`
		
		if [ "$sts_glastopf" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_dionaea" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_ragpicker" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_honssh" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_kippo" == '0' ];then
			echo " "
			exit 1
		fi
		
	}
###
#Main- _ - _ - _ - _ - _ - _ -_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ -
###
 log_chk
	case "$1" in
		start	) honey_start ;;
		stop	)  honey_stop ;;
		restart	) honey_stop;honey_start;;
		*		) " Usage: init_honeyPi [start|stop|status]"
